<?php
/*-----------------------------------------------------------------------------------*/
/*	AG ePDQ error codes
/*-----------------------------------------------------------------------------------*/
defined('ABSPATH') || die("No script kiddies please!");


if (class_exists('AG_errors')) {
	return;
}

class AG_errors
{


	/**
	 * ePDQ status code
	 *
	 * @param $code
	 * @return void
	 */
	public static function get_epdq_status_code($code)
	{

		if ($code == '')
			return;
		$codes =  array(
			0 => __('Incomplete or invalid', 'ag_epdq_server'),
			1 => __('Cancelled by client', 'ag_epdq_server'),
			2 => __('Authorisation refused', 'ag_epdq_server'),
			4 => __('Order stored', 'ag_epdq_server'),
			40 => __('Stored waiting external result', 'ag_epdq_server'),
			41 => __('Waiting client payment', 'ag_epdq_server'),
			5 => __('Authorised', 'ag_epdq_server'),
			51 => __('Authorisation waiting', 'ag_epdq_server'),
			52 => __('Authorisation not known', 'ag_epdq_server'),
			55 => __('Standby', 'ag_epdq_server'),
			56 => __('OK with scheduled payments', 'ag_epdq_server'),
			57 => __('Not OK with scheduled payments', 'ag_epdq_server'),
			59 => __('Author. to get manually', 'ag_epdq_server'),
			6 => __('Authorised and canceled', 'ag_epdq_server'),
			61 => __('Author. deletion waiting', 'ag_epdq_server'),
			62 => __('Author. deletion uncertain', 'ag_epdq_server'),
			63 => __('Author. deletion refused', 'ag_epdq_server'),
			64 => __('Authorised and cancelled', 'ag_epdq_server'),
			7 => __('Payment deleted', 'ag_epdq_server'),
			71 => __('Payment deletion pending', 'ag_epdq_server'),
			72 => __('Payment deletion uncertain', 'ag_epdq_server'),
			73 => __('Payment deletion refused', 'ag_epdq_server'),
			74 => __('Payment deleted (not accepted)', 'ag_epdq_server'),
			75 => __('Deletion processed by merchant', 'ag_epdq_server'),
			8 => __('Refund', 'ag_epdq_server'),
			81 => __('Refund pending', 'ag_epdq_server'),
			82 => __('Refund uncertain', 'ag_epdq_server'),
			83 => __('Refund refused', 'ag_epdq_server'),
			84 => __('Payment declined by the acquirer (will be debited)', 'ag_epdq_server'),
			85 => __('Refund processed by merchant', 'ag_epdq_server'),
			9 => __('Payment requested', 'ag_epdq_server'),
			91 => __('Payment processing', 'ag_epdq_server'),
			92 => __('Payment uncertain', 'ag_epdq_server'),
			93 => __('Payment refused', 'ag_epdq_server'),
			94 => __('Refund declined by the acquirer', 'ag_epdq_server'),
			95 => __('Payment processed by merchant', 'ag_epdq_server'),
			96 => __('Refund reversed', 'ag_epdq_server'),
			97 => __('Being processed - intermediate technical status', 'ag_epdq_server'),
			98 => __('Being processed - intermediate technical status', 'ag_epdq_server'),
			99 => __('Being processed - intermediate technical status', 'ag_epdq_server')
		);
		if (isset($codes[$code]))
			return $codes[$code];
		else
			return __('Unknown', 'ag_epdq_server');

	}


	/**
	 * ePDQ error code
	 *
	 * @param $code
	 * @return void
	 */
	public static function get_epdq_ncerror($code)
	{
		if ($code == '')
			return;

		$code = (int)$code;
		$ncerorr_list = array(

			20001001 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001002 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001003 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001004 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001005 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001006 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001007 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001008 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001009 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			20001010 => __('Authorisation failed. Please retry.', 'ag_epdq_server'),
			30001999 => __('Our payment system is currently under maintenance, please try later.', 'ag_epdq_server'),
			50001005 => __('Expiry date error.', 'ag_epdq_server'),
			50001007 => __('Requested operation code not permitted.', 'ag_epdq_server'),
			50001008 => __('Invalid time limit value.', 'ag_epdq_server'),
			50001010 => __('Invalid input date format.', 'ag_epdq_server'),
			50001013 => __('Unable to parse socket input stream.', 'ag_epdq_server'),
			50001014 => __('Error in parsing stream content.', 'ag_epdq_server'),
			50001015 => __('Currency error.', 'ag_epdq_server'),
			50001016 => __('Transaction still posted at end of wait.', 'ag_epdq_server'),
			50001017 => __('Sync value not compatible with delay value.', 'ag_epdq_server'),
			50001019 => __('Duplicate of a pre-existing transaction.', 'ag_epdq_server'),
			50001020 => __('Acceptance code required for transaction.', 'ag_epdq_server'),
			50001024 => __('Maintenance acquirer differs from original transaction acquirer.', 'ag_epdq_server'),
			50001025 => __('Maintenance merchant differs from original transaction merchant.', 'ag_epdq_server'),
			50001028 => __('Maintenance operation not appropriate for original transaction.', 'ag_epdq_server'),
			50001031 => __('Host application unknown for the transaction.', 'ag_epdq_server'),
			50001032 => __('Unable to perform requested operation with requested currency.', 'ag_epdq_server'),
			50001033 => __('Maintenance card number differs from original transaction card number.', 'ag_epdq_server'),
			50001034 => __('Operation code not permitted.', 'ag_epdq_server'),
			50001035 => __('Exception occurred in socket input stream processing.', 'ag_epdq_server'),
			50001036 => __('Card length does not correspond to an acceptable value for the brand.', 'ag_epdq_server'),
			50001036 => __('Card length does not correspond to an acceptable value for the brand.', 'ag_epdq_server'),
			50001068 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001069 => __('Invalid check for CardID and Brand.', 'ag_epdq_server'),
			50001070 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001116 => __('Unknown origin IP.', 'ag_epdq_server'),
			50001117 => __('No origin IP detected.', 'ag_epdq_server'),
			50001118 => __('Merchant configuration problem. Please contact support.', 'ag_epdq_server'),
			10001001 => __('Communication failure.', 'ag_epdq_server'),
			10001002 => __('Communication failure.', 'ag_epdq_server'),
			10001003 => __('Communication failure.', 'ag_epdq_server'),
			10001004 => __('Communication failure.', 'ag_epdq_server'),
			10001005 => __('Communication failure.', 'ag_epdq_server'),
			10001016 => __('Waiting for acquirer feedback.', 'ag_epdq_server'),
			10001018 => __('3XCB pending transaction awaiting for Final status.', 'ag_epdq_server'),
			20001001 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001002 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the status of the transaction within one working day. Please check the status later.', 'ag_epdq_server'),
			20001003 => __('We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction. Please check the status later.', 'ag_epdq_server'),
			20001004 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001005 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001006 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001007 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001008 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001009 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001010 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001101 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			20001104 => __('We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction. Please check the status later.', 'ag_epdq_server'),
			20001105 => __('We have received an unknown status for the transaction. We shall contact your acquirer and update the transaction status within one working day. Please check the status later.', 'ag_epdq_server'),
			20001111 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			20001998 => __('We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction. Please check the status later.', 'ag_epdq_server'),
			20002001 => __('Bank response origin cannot be checked.', 'ag_epdq_server'),
			20002002 => __('Beneficiary account number has been modified during processing.', 'ag_epdq_server'),
			20002003 => __('Amount has been modified during processing.', 'ag_epdq_server'),
			20002004 => __('Currency has been modified during processing.', 'ag_epdq_server'),
			20002005 => __('No feedback detected from the bank server.', 'ag_epdq_server'),
			30001001 => __('Payment refused by the financial institution.', 'ag_epdq_server'),
			30001002 => __('Duplicate request.', 'ag_epdq_server'),
			30001010 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30001011 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30001012 => __('Card blacklisted - Contact acquirer.', 'ag_epdq_server'),
			30001015 => __('There has been a connection error to the receiving bank. Please try later or choose another payment method.', 'ag_epdq_server'),
			30001016 => __('Transmission failure and/or Database error. The transaction could not be properly initialised in the send process (db access failures, etc.).', 'ag_epdq_server'),
			30001051 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30001054 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30001056 => __('Your merchant\'s acquirer is temporarily unavailable, please try later or choose another payment method.', 'ag_epdq_server'),
			30001057 => __('There has been a connection error to the receiving bank. Please try later or choose another payment method.', 'ag_epdq_server'),
			30001058 => __('There has been a connection error to the receiving bank. Please try later or choose another payment method.', 'ag_epdq_server'),
			30001060 => __('Acquirer has i`ndicated a failure during payment processing.', 'ag_epdq_server'),
			30001070 => __('RATEPAY Invalid Response Type (Failure).', 'ag_epdq_server'),
			30001071 => __('RATEPAY Missing Mandatory status code field (failure).', 'ag_epdq_server'),
			30001072 => __('RATEPAY Missing Mandatory Result code field (failure).', 'ag_epdq_server'),
			30001073 => __('RATEPAY Response parsing Failed.', 'ag_epdq_server'),
			30001090 => __('CVC check required by front end and returned invalid by acquirer.', 'ag_epdq_server'),
			30001091 => __('Postcode check required by front end and returned invalid by acquirer.', 'ag_epdq_server'),
			30001092 => __('Address check required by frontend and returned as invalid by acquirer.', 'ag_epdq_server'),
			30001100 => __('Unauthorised customer country.', 'ag_epdq_server'),
			30001101 => __('IP country differs from card country.', 'ag_epdq_server'),
			30001102 => __('Number of different countries too high.', 'ag_epdq_server'),
			30001103 => __('unauthorised card country.', 'ag_epdq_server'),
			30001104 => __('unauthorised IP address country.', 'ag_epdq_server'),
			30001105 => __('Anonymous proxy.', 'ag_epdq_server'),
			30001110 => __('If the problem persists, please contact Support or go to paysafecard\'s card balance page (https://customer.cc.at.paysafecard.com/psccustomer/GetWelcomePanelServlet?language=en), to see when the amount reserved on your card will be available again.', 'ag_epdq_server'),
			30001120 => __('IP address on merchant\'s blacklist.', 'ag_epdq_server'),
			30001130 => __('BIN on merchant\'s blacklist.', 'ag_epdq_server'),
			30001131 => __('Wrong BIN for 3xCB.', 'ag_epdq_server'),
			30001140 => __('Card on merchant\'s blacklist.', 'ag_epdq_server'),
			30001141 => __('E-mail blacklisted.', 'ag_epdq_server'),
			30001142 => __('Passenger name blacklisted.', 'ag_epdq_server'),
			30001143 => __('Cardholder name blacklisted.', 'ag_epdq_server'),
			30001144 => __('Passenger name different from owner name.', 'ag_epdq_server'),
			30001145 => __('Time to departure too short.', 'ag_epdq_server'),
			30001149 => __('Card Configured in Card Supplier Limit for another relation (CSL).', 'ag_epdq_server'),
			30001150 => __('Card not configured in the system for this customer (CSL).', 'ag_epdq_server'),
			30001151 => __('REF1 not allowed for this relationship (Contract number).', 'ag_epdq_server'),
			30001152 => __('Card/Supplier Amount limit reached (CSL).', 'ag_epdq_server'),
			30001153 => __('Card not permitted for this supplier (Date out of contractual limits).', 'ag_epdq_server'),
			30001154 => __('You have reached the permitted usage limit.', 'ag_epdq_server'),
			30001155 => __('You have reached the permitted usage limit.', 'ag_epdq_server'),
			30001156 => __('You have reached the permitted usage limit.', 'ag_epdq_server'),
			30001157 => __('Unauthorised IP country for itinerary.', 'ag_epdq_server'),
			30001158 => __('e-mail usage limit reached.', 'ag_epdq_server'),
			30001159 => __('Unauthorised card country/IP country combination.', 'ag_epdq_server'),
			30001160 => __('Postcode in high-risk group.', 'ag_epdq_server'),
			30001161 => __('generic blacklist match.', 'ag_epdq_server'),
			30001162 => __('Invoicing Address is a PO Box.', 'ag_epdq_server'),
			30001163 => __('Airport in high-risk group.', 'ag_epdq_server'),
			30001164 => __('Shipping Method in high-risk group.', 'ag_epdq_server'),
			30001165 => __('Shipping Method Details in high-risk group.', 'ag_epdq_server'),
			30001166 => __('Product Category in high-risk group.', 'ag_epdq_server'),
			30001167 => __('Subbrand in high-risk group.', 'ag_epdq_server'),
			30001168 => __('Issuer Number in high-risk group.', 'ag_epdq_server'),
			30001169 => __('Time to delivery too short.', 'ag_epdq_server'),
			30001180 => __('maximum scoring reached.', 'ag_epdq_server'),
			30001997 => __('Authorisation cancelled by simulator.', 'ag_epdq_server'),
			30001998 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			30001999 => __('There has been a connection error with the receiving bank. Please try later or choose another payment method.', 'ag_epdq_server'),
			30002001 => __('Payment refused by the financial institution.', 'ag_epdq_server'),
			30002001 => __('Payment refused by the financial institution.', 'ag_epdq_server'),
			30021001 => __('Please call the acquirer support call number.', 'ag_epdq_server'),
			30022001 => __('Payment must be approved by the acquirer prior to execution.', 'ag_epdq_server'),
			30031001 => __('Invalid merchant number.', 'ag_epdq_server'),
			30041001 => __('Retain card.', 'ag_epdq_server'),
			30051001 => __('Authorisation declined.', 'ag_epdq_server'),
			30051002 => __('Voor vragen over uw afwijzing kunt u contact opnemen met de @STARTURL@http://www.afterpay.nl/consument-contact@TXTURL@Klantenservice van AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051009 => __('It is possible that you may not have completed all the required information (correctly) during the order process.', 'ag_epdq_server'),
			30051010 => __('because your age is under 18. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=2@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051011 => __('because your address could not be validated. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=3@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051012 => __('because your emailadres is invalid. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=4@TXTURL@website van AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051013 => __('because the order amount extends the limit for first time AfterPay users. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=5@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051014 => __('because there are currently too many outstanding payments at AfterPay. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=6@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051015 => __('because your chamber of commerce number could not be validated. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=7@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051016 => __('because the order amount is too low. For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=8@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30051017 => __('For more information please visit @STARTURL@http://www.afterpay.nl/rej.php?LAN=$LANGUAGE$&TEMPLATE=1@TXTURL@website of AfterPay@ENDURL@.', 'ag_epdq_server'),
			30071001 => __('Retain card - special conditions.', 'ag_epdq_server'),
			30121001 => __('Invalid transaction.', 'ag_epdq_server'),
			30131001 => __('Invalid amount.', 'ag_epdq_server'),
			30131002 => __('You have reached the permitted limit.', 'ag_epdq_server'),
			30141001 => __('Invalid card number.', 'ag_epdq_server'),
			30151001 => __('Unknown acquiring institution.', 'ag_epdq_server'),
			30171001 => __('Payment method cancelled by the customer.', 'ag_epdq_server'),
			30171002 => __('The maximum time allowed has elapsed.', 'ag_epdq_server'),
			30191001 => __('Please try again later.', 'ag_epdq_server'),
			30201001 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30301001 => __('Invalid format.', 'ag_epdq_server'),
			30311001 => __('Unknown acquirer ID.', 'ag_epdq_server'),
			30331001 => __('Card expired.', 'ag_epdq_server'),
			30341001 => __('Suspicion of fraud.', 'ag_epdq_server'),
			30341001 => __('Suspicion of fraud.', 'ag_epdq_server'),
			30341002 => __('Suspicion of fraud (3rdMan).', 'ag_epdq_server'),
			30341003 => __('Suspicion of fraud (Perseuss).', 'ag_epdq_server'),
			30341004 => __('Suspicion of fraud (ETHOCA).', 'ag_epdq_server'),
			30341005 => __('Suspicion of fraud (Expert).', 'ag_epdq_server'),
			30381001 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30401001 => __('Invalid function.', 'ag_epdq_server'),
			30411001 => __('Lost card.', 'ag_epdq_server'),
			30431001 => __('Stolen card. Pick up.', 'ag_epdq_server'),
			30511001 => __('Insufficient funds.', 'ag_epdq_server'),
			30521001 => __('No Authorisation. Please contact your card issuer.', 'ag_epdq_server'),
			30541001 => __('Card expired.', 'ag_epdq_server'),
			30551001 => __('Invalid PIN.', 'ag_epdq_server'),
			30561001 => __('Card not in authoriser\'s database.', 'ag_epdq_server'),
			30571001 => __('Transaction not permitted on card.', 'ag_epdq_server'),
			30581001 => __('Transaction not permitted on this terminal.', 'ag_epdq_server'),
			30591001 => __('Suspicion of fraud.', 'ag_epdq_server'),
			30601001 => __('The merchant should contact the acquirer.', 'ag_epdq_server'),
			30611001 => __('Amount exceeds card limit.', 'ag_epdq_server'),
			30621001 => __('Restricted card.', 'ag_epdq_server'),
			30631001 => __('Security policy not respected.', 'ag_epdq_server'),
			30641001 => __('Amount changed from ref. transaction.', 'ag_epdq_server'),
			30681001 => __('The maximum allowed time has elapsed.', 'ag_epdq_server'),
			30751001 => __('Incorrect PIN entered too many times.', 'ag_epdq_server'),
			30761001 => __('Already disputed by cardholder.', 'ag_epdq_server'),
			30771001 => __('PIN entry required.', 'ag_epdq_server'),
			30811001 => __('Message flow error.', 'ag_epdq_server'),
			30821001 => __('Authorisation centre unavailable.', 'ag_epdq_server'),
			30831001 => __('Authorisation centre unavailable.', 'ag_epdq_server'),
			30901001 => __('Temporary system shutdown.', 'ag_epdq_server'),
			30911001 => __('Acquirer unavailable.', 'ag_epdq_server'),
			30921001 => __('Invalid card type for acquirer.', 'ag_epdq_server'),
			30941001 => __('Duplicate transaction.', 'ag_epdq_server'),
			30961001 => __('Processing temporarily not possible.', 'ag_epdq_server'),
			30971001 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			30981001 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			31011001 => __('Unknown acceptance code.', 'ag_epdq_server'),
			31021001 => __('Invalid currency.', 'ag_epdq_server'),
			31031001 => __('Acceptance code missing.', 'ag_epdq_server'),
			31041001 => __('Inactive card.', 'ag_epdq_server'),
			31051001 => __('Merchant not active.', 'ag_epdq_server'),
			31061001 => __('Invalid expiry date.', 'ag_epdq_server'),
			31071001 => __('Interrupted host communication.', 'ag_epdq_server'),
			31081001 => __('Card refused.', 'ag_epdq_server'),
			31091001 => __('Invalid password.', 'ag_epdq_server'),
			31101001 => __('Plafond transaction (majoré du bonus) dépassé.', 'ag_epdq_server'),
			31111001 => __('Plafond mensuel (majoré du bonus) dépassé.', 'ag_epdq_server'),
			31121001 => __('Plafond centre de facturation dépassé.', 'ag_epdq_server'),
			31131001 => __('Plafond entreprise dépassé.', 'ag_epdq_server'),
			31141001 => __('Code MCC du fournisseur non autorisé pour la carte.', 'ag_epdq_server'),
			31151001 => __('Numéro SIRET du fournisseur non autorisé pour la carte.', 'ag_epdq_server'),
			31161001 => __('This is not a valid online bank account.', 'ag_epdq_server'),
			32001004 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			32001105 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			34011001 => __('Bezahlung mit RatePAY nicht möglich.', 'ag_epdq_server'),
			39991001 => __('A technical problem has occurred. Please contact your acquirer\'s helpdesk.', 'ag_epdq_server'),
			40001001 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001002 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001003 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001004 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001005 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001006 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001007 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001008 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001009 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001010 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001011 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			40001012 => __('There has been a connection error with the receiving bank. Please try later or choose another payment method.', 'ag_epdq_server'),
			40001013 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			40001016 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			40001018 => __('A technical problem has occurred. Please try again.', 'ag_epdq_server'),
			40001019 => __('Sorry, an error has occurred during processing. Please retry the transaction (using the Back button of the browser). If the problem persists, contact your merchant\'s helpdesk.', 'ag_epdq_server'),
			40001020 => __(' Sorry, an error occurred during processing. Please retry the operation (using the Back button of the browser). If the problem persists, please contact your merchant\'s helpdesk.', 'ag_epdq_server'),
			40001050 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			40001133 => __('Authentication failed. Incorrect signature for your bank\'s access control server.', 'ag_epdq_server'),
			40001134 => __('Authentication failed. Please retry or cancel.', 'ag_epdq_server'),
			40001135 => __('Authentication temporarily unavailable. Please retry or cancel.', 'ag_epdq_server'),
			40001136 => __('Technical problem with your browser. Please retry or cancel.', 'ag_epdq_server'),
			40001137 => __('Your bank is temporarily unavailable. Please try again later or choose another payment method.', 'ag_epdq_server'),
			40001998 => __('Temporary technical problem. Please retry later.', 'ag_epdq_server'),
			50001001 => __('Unknown card type.', 'ag_epdq_server'),
			50001002 => __('Card number format check failed for given card number.', 'ag_epdq_server'),
			50001003 => __('Merchant data error.', 'ag_epdq_server'),
			50001004 => __('Merchant identification missing.', 'ag_epdq_server'),
			50001005 => __('Expiry date error.', 'ag_epdq_server'),
			50001006 => __('Amount is not a number.', 'ag_epdq_server'),
			50001007 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001008 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001009 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001010 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001011 => __('Brand not supported for that merchant.', 'ag_epdq_server'),
			50001012 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001013 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001014 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001015 => __('Invalid currency code.', 'ag_epdq_server'),
			50001016 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001017 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001018 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001019 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001020 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001021 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001022 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001023 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001024 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001025 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001026 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001027 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001028 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001029 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001030 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001031 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001032 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001033 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001034 => __('A technical has problem occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001035 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001036 => __('Incorrect card length for the brand.', 'ag_epdq_server'),
			50001037 => __('Purchasing card number for a standard merchant.', 'ag_epdq_server'),
			50001038 => __('You should use a purchasing card for this transaction.', 'ag_epdq_server'),
			50001039 => __('Details sent for a non-purchasing card merchant. Please contact the helpdesk.', 'ag_epdq_server'),
			50001040 => __('Details not sent for a purchasing card transaction. Please contact the helpdesk.', 'ag_epdq_server'),
			50001041 => __('Payment detail validation failed.', 'ag_epdq_server'),
			50001042 => __('Sum of given transaction amounts (tax, discount, delivery, net, etc.) does not match total.', 'ag_epdq_server'),
			50001043 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001044 => __('No acquirer configured for this operation.', 'ag_epdq_server'),
			50001045 => __('No UID configured for this operation.', 'ag_epdq_server'),
			50001046 => __('Operation not permitted for the merchant.', 'ag_epdq_server'),
			50001047 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001048 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001049 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001050 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001051 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001052 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001053 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001054 => __('Card number incorrect or incompatible.', 'ag_epdq_server'),
			50001055 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001056 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001057 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001058 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001059 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001060 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001061 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001062 => __('A technical problem has occurred. Please contact the helpdesk.', 'ag_epdq_server'),
			50001063 => __('Card Issue Number does not correspond to range or is not present.', 'ag_epdq_server'),
			50001064 => __('Start Date invalid or not present.', 'ag_epdq_server'),
			50001066 => __('Invalid CVC code format.', 'ag_epdq_server'),
			50001067 => __('The merchant is not registered for 3D-Secure.', 'ag_epdq_server'),
			50001068 => __('Invalid card number or account number (PAN).', 'ag_epdq_server'),
			50001069 => __('Invalid CardID and Brand match.', 'ag_epdq_server'),
			50001070 => __('The ECI value is either not supported or conflicts with other transaction data.', 'ag_epdq_server'),
			50001071 => __('Incomplete TRN demat.', 'ag_epdq_server'),
			50001072 => __('Incomplete PAY demat.', 'ag_epdq_server'),
			50001073 => __('No demat APP.', 'ag_epdq_server'),
			50001074 => __('Authorisation period expired.', 'ag_epdq_server'),
			50001075 => __('VERRes was an error message.', 'ag_epdq_server'),
			50001076 => __('DCP amount greater than authorisation amount.', 'ag_epdq_server'),
			50001077 => __('Details negative amount.', 'ag_epdq_server'),
			50001078 => __('Details negative quantity.', 'ag_epdq_server'),
			50001079 => __('Could not decode/decompress received PARes (3D-Secure).', 'ag_epdq_server'),
			50001080 => __('Received PARes was an error message from ACS (3D-Secure).', 'ag_epdq_server'),
			50001081 => __('Received PARes format was invalid according to the 3DS specifications (3D-Secure).', 'ag_epdq_server'),
			50001082 => __('PAReq/PARes reconciliation failure (3D-Secure).', 'ag_epdq_server'),
			50001084 => __('Maximum amount reached.', 'ag_epdq_server'),
			50001087 => __('This transaction requires authentication. Please check with your bank.', 'ag_epdq_server'),
			50001090 => __('CVC missing at input, but CVC check requested.', 'ag_epdq_server'),
			50001091 => __('Postcode missing at input, but postcode check requested.', 'ag_epdq_server'),
			50001092 => __('Address missing at input, but Address check requested.', 'ag_epdq_server'),
			50001093 => __('Partial capture not allowed.', 'ag_epdq_server'),
			50001095 => __('Invalid date of birth.', 'ag_epdq_server'),
			50001096 => __('Invalid commodity code.', 'ag_epdq_server'),
			50001097 => __('The requested currency and brand are incompatible.', 'ag_epdq_server'),
			50001111 => __('Data validation error.', 'ag_epdq_server'),
			50001113 => __('This order has already been processed.', 'ag_epdq_server'),
			50001114 => __('Error in accessing the pre-payment check page.', 'ag_epdq_server'),
			50001115 => __('Request not received in secure mode.', 'ag_epdq_server'),
			50001116 => __('Unknown IP address origin.', 'ag_epdq_server'),
			50001117 => __('No IP address origin.', 'ag_epdq_server'),
			50001118 => __('PSPID not found or incorrect.', 'ag_epdq_server'),
			50001119 => __('Password incorrect or disabled due to number of errors.', 'ag_epdq_server'),
			50001120 => __('Invalid currency.', 'ag_epdq_server'),
			50001121 => __('Invalid number of decimals for the currency.', 'ag_epdq_server'),
			50001122 => __('Currency not accepted by the merchant.', 'ag_epdq_server'),
			50001123 => __('Card type not active.', 'ag_epdq_server'),
			50001124 => __('Number of lines doesn\'t match the number of payments.', 'ag_epdq_server'),
			50001125 => __('Format validation error.', 'ag_epdq_server'),
			50001126 => __('Overflow in data capture requests for the original order.', 'ag_epdq_server'),
			50001127 => __('Incorrect original order status.', 'ag_epdq_server'),
			50001128 => __('missing authorisation code for unauthorised order.', 'ag_epdq_server'),
			50001129 => __('Overflow in refunds requests.', 'ag_epdq_server'),
			50001130 => __('Original order access error.', 'ag_epdq_server'),
			50001131 => __('Original history item access error.', 'ag_epdq_server'),
			50001132 => __('The selected Catalogue is empty.', 'ag_epdq_server'),
			50001133 => __('Duplicate request.', 'ag_epdq_server'),
			50001134 => __('Authentication failed. Please retry or cancel.', 'ag_epdq_server'),
			50001135 => __('Authentication temporarily unavailable. Please retry or cancel.', 'ag_epdq_server'),
			50001136 => __('Technical problem with your browser. Please retry or cancel.', 'ag_epdq_server'),
			50001137 => __('Your bank is temporarily unavailable. Please try again later or choose another payment method.', 'ag_epdq_server'),
			50001150 => __('Fraud Detection: technical error (invalid IP).', 'ag_epdq_server'),
			50001151 => __('Fraud detection: technical error (IPCTY unknown or error).', 'ag_epdq_server'),
			50001152 => __('Fraud detection: technical error (CCCTY unknown or error).', 'ag_epdq_server'),
			50001153 => __('Overflow in redo-authorisation requests.', 'ag_epdq_server'),
			50001170 => __('Dynamic BIN check failed.', 'ag_epdq_server'),
			50001171 => __('Dynamic country check failed.', 'ag_epdq_server'),
			50001172 => __('Amadeus signature error.', 'ag_epdq_server'),
			50001174 => __('Cardholder Name is too long.', 'ag_epdq_server'),
			50001175 => __('Name contains invalid characters.', 'ag_epdq_server'),
			50001176 => __('Card number is too long.', 'ag_epdq_server'),
			50001177 => __('Card number contains non-numeric info.', 'ag_epdq_server'),
			50001178 => __('Card Number Empty.', 'ag_epdq_server'),
			50001179 => __('CVC too long.', 'ag_epdq_server'),
			50001180 => __('CVC contains non-numeric info.', 'ag_epdq_server'),
			50001181 => __('Expiry date contains non-numeric info.', 'ag_epdq_server'),
			50001182 => __('Invalid expiry month.', 'ag_epdq_server'),
			50001183 => __('Expiry date must be in the future.', 'ag_epdq_server'),
			50001184 => __('SHA Mismatch.', 'ag_epdq_server'),
			50001186 => __('Operation not permitted.', 'ag_epdq_server'),
			50001187 => __('Operation not permitted.', 'ag_epdq_server'),
			50001205 => __('Missing mandatory fields in invoicing address.', 'ag_epdq_server'),
			50001206 => __('Missing mandatory date of birth field.', 'ag_epdq_server'),
			50001207 => __('Missing required shopping basket details.', 'ag_epdq_server'),
			50001208 => __('Missing social security number.', 'ag_epdq_server'),
			50001209 => __('Invalid country code.', 'ag_epdq_server'),
			50001210 => __('Missing annual salary.', 'ag_epdq_server'),
			50001211 => __('Missing gender.', 'ag_epdq_server'),
			50001212 => __('Missing e-mail.', 'ag_epdq_server'),
			50001213 => __('Missing IP address.', 'ag_epdq_server'),
			50001214 => __('Missing part-payment campaign ID.', 'ag_epdq_server'),
			50001215 => __('Missing invoice number.', 'ag_epdq_server'),
			50001216 => __('The alias must be different to the card number.', 'ag_epdq_server'),
			50001217 => __('Invalid details for shopping basket calculation.', 'ag_epdq_server'),
			50001218 => __('No Refunds allowed.', 'ag_epdq_server'),
			50001220 => __('Invalid format of phone number.', 'ag_epdq_server'),
			50001221 => __('Invalid ZIP format.', 'ag_epdq_server'),
			50001222 => __('Firstname or/and lastname missing.', 'ag_epdq_server'),
			50001223 => __('Firstname and/or lastname format invalid.', 'ag_epdq_server'),
			50001224 => __('The phone number is missing.', 'ag_epdq_server'),
			50001225 => __('Invalid email format.', 'ag_epdq_server'),
			50001300 => __('Wrong brand/payment method.', 'ag_epdq_server'),
			50001301 => __('Wrong account number format.', 'ag_epdq_server'),
			50001302 => __('RFP operation code is only permitted with scheduled payments.', 'ag_epdq_server'),
			50001303 => __('RFP operation code not permitted for a Disputed payment.', 'ag_epdq_server'),
			50001304 => __('RFP operation code not permitted - Unpaid amounts.', 'ag_epdq_server'),
			55555555 => __('An error occurred.', 'ag_epdq_server'),
			60000001 => __('account number unknown.', 'ag_epdq_server'),
			60000003 => __('not credited dd-mm-yy.', 'ag_epdq_server'),
			60000005 => __('name/number do not match.', 'ag_epdq_server'),
			60000007 => __('account number blocked.', 'ag_epdq_server'),
			60000008 => __('specific direct debit block.', 'ag_epdq_server'),
			60000009 => __('account number WKA.', 'ag_epdq_server'),
			60000010 => __('administrative reason.', 'ag_epdq_server'),
			60000011 => __('account number expired.', 'ag_epdq_server'),
			60000012 => __('no direct debit authorisation.', 'ag_epdq_server'),
			60000013 => __('debit not approved.', 'ag_epdq_server'),
			60000014 => __('double payment.', 'ag_epdq_server'),
			60000018 => __('name/address/city not entered.', 'ag_epdq_server'),
			60001001 => __('no original direct debit for revocation.', 'ag_epdq_server'),
			60001002 => __('payer\'s account number format error.', 'ag_epdq_server'),
			60001004 => __('payer\'s account at different bank.', 'ag_epdq_server'),
			60001005 => __('payee\'s account at different bank.', 'ag_epdq_server'),
			60001006 => __('payee\'s account number format error.', 'ag_epdq_server'),
			60001007 => __('payer\'s account number blocked.', 'ag_epdq_server'),
			60001008 => __('payer\'s account number expired.', 'ag_epdq_server'),
			60001009 => __('payee\'s account number expired.', 'ag_epdq_server'),
			60001010 => __('direct debit not possible.', 'ag_epdq_server'),
			60001011 => __('creditor payment not possible.', 'ag_epdq_server'),
			60001012 => __('payer\'s account number unknown WKA-number.', 'ag_epdq_server'),
			60001013 => __('payee\'s account number unknown WKA-number.', 'ag_epdq_server'),
			60001014 => __('WKA transaction not permitted.', 'ag_epdq_server'),
			60001015 => __('revocation period expired.', 'ag_epdq_server'),
			60001017 => __('incorrect revocation reason.', 'ag_epdq_server'),
			60001018 => __('original run number not numeric.', 'ag_epdq_server'),
			60001019 => __('payment ID incorrect.', 'ag_epdq_server'),
			60001020 => __('amount not numeric.', 'ag_epdq_server'),
			60001021 => __('zero amount not permitted.', 'ag_epdq_server'),
			60001022 => __('negative amount not permitted.', 'ag_epdq_server'),
			60001023 => __('payer and payee giro account number.', 'ag_epdq_server'),
			60001025 => __('processing code (verwerkingscode) incorrect.', 'ag_epdq_server'),
			60001028 => __('revocation not permitted.', 'ag_epdq_server'),
			60001029 => __('guaranteed direct debit on giro account number.', 'ag_epdq_server'),
			60001030 => __('NBC transaction type incorrect.', 'ag_epdq_server'),
			60001031 => __('description too long.', 'ag_epdq_server'),
			60001032 => __('book account number not issued.', 'ag_epdq_server'),
			60001034 => __('book account number incorrect.', 'ag_epdq_server'),
			60001035 => __('payer\'s account number not numeric.', 'ag_epdq_server'),
			60001036 => __('payer\'s account number not eleven-proof.', 'ag_epdq_server'),
			60001037 => __('payer\'s account number not issued.', 'ag_epdq_server'),
			60001039 => __('payer\'s account number of DNB/BGC/BLA.', 'ag_epdq_server'),
			60001040 => __('payee\'s account number not numeric.', 'ag_epdq_server'),
			60001041 => __('payee\'s account number not eleven-proof.', 'ag_epdq_server'),
			60001042 => __('payee\'s account number not issued.', 'ag_epdq_server'),
			60001044 => __('payee\'s account number unknown.', 'ag_epdq_server'),
			60001050 => __('payee\'s name missing.', 'ag_epdq_server'),
			60001051 => __('indicate payee\'s bank account number instead of 3102.', 'ag_epdq_server'),
			60001052 => __('no direct debit contract.', 'ag_epdq_server'),
			60001053 => __('amount beyond limits.', 'ag_epdq_server'),
			60001054 => __('selective direct debit block.', 'ag_epdq_server'),
			60001055 => __('original run number unknown.', 'ag_epdq_server'),
			60001057 => __('payer\'s name missing.', 'ag_epdq_server'),
			60001058 => __('payee\'s account number missing.', 'ag_epdq_server'),
			60001059 => __('restore not permitted.', 'ag_epdq_server'),
			60001060 => __('bank\'s reference (navraaggegeven) missing.', 'ag_epdq_server'),
			60001061 => __('BEC/GBK number incorrect.', 'ag_epdq_server'),
			60001062 => __('BEC/GBK code incorrect.', 'ag_epdq_server'),
			60001087 => __('book account number not numeric.', 'ag_epdq_server'),
			60001090 => __('cancelled on request.', 'ag_epdq_server'),
			60001091 => __('cancellation order executed.', 'ag_epdq_server'),
			60001092 => __('cancelled instead of ended.', 'ag_epdq_server'),
			60001093 => __('book account number is a shortened account number.', 'ag_epdq_server'),
			60001094 => __('instructing party and payer account numbers do not match.', 'ag_epdq_server'),
			60001095 => __('payee unknown GBK acceptor.', 'ag_epdq_server'),
			60001097 => __('instructing party and payee account numbers do not match.', 'ag_epdq_server'),
			60001099 => __('clearing not permitted.', 'ag_epdq_server'),
			60001101 => __('payer\'s account number has no spaces.', 'ag_epdq_server'),
			60001102 => __('PAN length not numeric.', 'ag_epdq_server'),
			60001103 => __('PAN length outside limits.', 'ag_epdq_server'),
			60001104 => __('track number not numeric.', 'ag_epdq_server'),
			60001105 => __('track number not valid.', 'ag_epdq_server'),
			60001106 => __('PAN sequence number not numeric.', 'ag_epdq_server'),
			60001107 => __('domestic PAN not numeric.', 'ag_epdq_server'),
			60001108 => __('domestic PAN not eleven-proof.', 'ag_epdq_server'),
			60001109 => __('domestic PAN not issued.', 'ag_epdq_server'),
			60001110 => __('foreign PAN not numeric.', 'ag_epdq_server'),
			60001111 => __('card validity date not numeric.', 'ag_epdq_server'),
			60001112 => __('book period number (boekperiodenr) not numeric.', 'ag_epdq_server'),
			60001113 => __('transaction number not numeric.', 'ag_epdq_server'),
			60001114 => __('transaction time not numeric.', 'ag_epdq_server'),
			60001115 => __('invalid transaction time.', 'ag_epdq_server'),
			60001116 => __('transaction date not numeric.', 'ag_epdq_server'),
			60001117 => __('invalid transaction date.', 'ag_epdq_server'),
			60001118 => __('STAN not numeric.', 'ag_epdq_server'),
			60001119 => __('instructing party\'s name missing.', 'ag_epdq_server'),
			60001120 => __('foreign amount (bedrag-vv) not numeric.', 'ag_epdq_server'),
			60001122 => __('rate (verrekenkoers) not numeric.', 'ag_epdq_server'),
			60001125 => __('number of decimals (aantaldecimalen) incorrect.', 'ag_epdq_server'),
			60001126 => __('tariff (tarifering) not B/O/S.', 'ag_epdq_server'),
			60001127 => __('domestic costs (kostenbinnenland) not numeric.', 'ag_epdq_server'),
			60001128 => __('domestic costs (kostenbinnenland) not higher than zero.', 'ag_epdq_server'),
			60001129 => __('foreign costs (kostenbuitenland) not numeric.', 'ag_epdq_server'),
			60001130 => __('foreign costs (kostenbuitenland) not higher than zero.', 'ag_epdq_server'),
			60001131 => __('domestic costs (kostenbinnenland) not zero.', 'ag_epdq_server'),
			60001132 => __('foreign costs (kostenbuitenland) not zero.', 'ag_epdq_server'),
			60001134 => __('Euro record not completed.', 'ag_epdq_server'),
			60001135 => __('Customer currency incorrect.', 'ag_epdq_server'),
			60001136 => __('NLG amount not numeric.', 'ag_epdq_server'),
			60001137 => __('NLG amount not higher than zero.', 'ag_epdq_server'),
			60001138 => __('NLG amount not equal to Amount.', 'ag_epdq_server'),
			60001139 => __('NLG amount incorrectly converted.', 'ag_epdq_server'),
			60001140 => __('EUR amount not numeric.', 'ag_epdq_server'),
			60001141 => __('EUR amount not greater than zero.', 'ag_epdq_server'),
			60001142 => __('EUR amount not equal to Amount.', 'ag_epdq_server'),
			60001143 => __('EUR amount incorrectly converted.', 'ag_epdq_server'),
			60001144 => __('Customer currency not NLG.', 'ag_epdq_server'),
			60001145 => __('rate euro-vv (Koerseuro-vv) not numeric.', 'ag_epdq_server'),
			60001146 => __('comma rate euro-vv (Kommakoerseuro-vv) incorrect.', 'ag_epdq_server'),
			60001147 => __('invalid acceptgiro distributor.', 'ag_epdq_server'),
			60001148 => __('Original run number and/or BRN missing.', 'ag_epdq_server'),
			60001149 => __('Amount/Account number/ BRN different.', 'ag_epdq_server'),
			60001150 => __('Direct debit already revoked/restored.', 'ag_epdq_server'),
			60001151 => __('Direct debit already reversed/revoked/restored.', 'ag_epdq_server'),
			60001153 => __('Payer\'s account number not know.', 'ag_epdq_server'),
		);


		if (isset($ncerorr_list[$code]))
			return $ncerorr_list[$code];
		else
			return __('Unknown', 'ag_epdq_server');

	}
}
